### ISSUE TITLE
Error is system logs

### ISSUE THREAD

**Issue by LawlyPopz** [Gocnak/Botnak#121]
[3:58 AM] SYS: java.io.IOException: Server returned HTTP response code: 422 for URL: https://api.twitch.tv/kraken/channels/lawlypopzcastleclash/subscriptions?oauth_token=blhblahbalbhablah&limit=100&offset=0
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1839)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1440)
	at sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:254)
	at java.net.URL.openStream(URL.java:1038)
	at util.settings.SubscriberManager.scanInitialSubscribers(SubscriberManager.java:194)
	at util.settings.Settings.lambda$load$0(Settings.java:214)
	at util.settings.Settings$$Lambda$55/128134029.run(Unknown Source)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

**Comment by PopRocksJesus** [comment]
you need to take this off it has your oauth in it

**Comment by Jordod** [comment]
m8, you might wanna remove that ouath bit in the link, it allows people to login to your account

**Comment by PopRocksJesus** [comment]
also this is just teeling you you don't have any subs

**Comment by Gocnak** [comment]
Well I edited the oauth out, be weary of posting that in the future. You'll be reauthorizing anyways though:

This issue comes from ticking the "Read Subscribers" box on the GUIAuthorizeAccount when you're not a partner. I can catch this error and turn off that Oauth feature, so this error is actually helpful for that, thank you.
