### ISSUE TITLE
Cant log in to account.

### ISSUE THREAD

**Issue by tsteinholz** [Gocnak/Botnak#73]
After puting in the streamer account i got the error : 
` Exception in thread "Thread-7" java.lang.NullPointerException
	at lib.pircbot.org.jibble.pircbot.PircBot.connect(PircBot.java:204)
	at irc.account.AccountManager.run(AccountManager.java:104) `

**Comment by Gocnak** [comment]
Many thanks, this is a null pointer with the channel manager that will be fixed in the next version.
